"""create initial tables

Revision ID: 3162f3648d59
Revises: 
Create Date: 2026-07-02 11:28:01.545458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3162f3648d59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('books',
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('extractor_name', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_client_id'), 'books', ['client_id'], unique=False)
    op.create_index(op.f('ix_books_grade'), 'books', ['grade'], unique=False)
    op.create_index(op.f('ix_books_lang'), 'books', ['lang'], unique=False)
    op.create_index(op.f('ix_books_subject'), 'books', ['subject'], unique=False)
    op.create_table('chapters',
    sa.Column('chapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id'),
    sa.UniqueConstraint('book_id', 'name')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('book_id', 'chapter_id', 'name')
    )
    op.create_index(op.f('ix_sections_book_id'), 'sections', ['book_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('context_snippet', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunks_book_id'), 'chunks', ['book_id'], unique=False)
    op.create_index(op.f('ix_chunks_client_id'), 'chunks', ['client_id'], unique=False)
    op.create_index(op.f('ix_chunks_lang'), 'chunks', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_lang'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_client_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_book_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_sections_book_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_books_subject'), table_name='books')
    op.drop_index(op.f('ix_books_lang'), table_name='books')
    op.drop_index(op.f('ix_books_grade'), table_name='books')
    op.drop_index(op.f('ix_books_client_id'), table_name='books')
    op.drop_table('books')
    op.drop_table('clients')
    # ### end Alembic commands ###
